services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WebCapsule\Bundle\DiscordWebhooks\:
    resource: '../../*'
    exclude: '../../{Entity,Tests,Resources}'

  WebCapsule\Bundle\DiscordWebhooks\Client\WebhookClient:
    abstract: true
    arguments: [null, null]
